PierresTreats/Models/Treat.cs
using System.Collections.Generic; 
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models;

public class Treat
{
  public int TreatId { get; set; }
  [Required(ErrorMessage = "The treat must have a name")]
  public string Name { get; set; }
  public List<FlavorTreat> JoinEntities { get; }
  public ApplicationUser User { get; set; }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult ReadOnly(int id)
    {
      if (User.Identity.IsAuthenticated)
      {
        return RedirectToAction("Details", new {id = id});
      }
      else
      {
        Treat thisTreat = _db.Treats
            .Include(t => t.JoinEntities)
            .ThenInclude(j => j.Flavor)
            .FirstOrDefault(t => t.TreatId == id);
        List<string> names = new List<string>();
        foreach (FlavorTreat join in _db.FlavorTreats)
        {
          if (join.TreatId == thisTreat.TreatId)
          {
            names.Add(join.Flavor.Name);
          }
        }
        ViewBag.Names = names;
        return View (thisTreat);
      }
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {        
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index", "Home");
      }
    }
    public ActionResult Details (int id)
    {      
      Treat thisTreat = _db.Treats
            .Include(tr => tr.JoinEntities)
            .FirstOrDefault(tr => tr.TreatId == id);      
      List<Flavor> select = new List<Flavor>();
      foreach (Flavor flavor in _db.Flavors)
      {          
        select.Add(flavor);        
      }
      foreach (FlavorTreat join in thisTreat.JoinEntities)
      {
        select.Remove(join.Flavor);
      }      
      ViewBag.FlavorId = new SelectList(select, "FlavorId", "Name");      
      return View(thisTreat);
    }

    [HttpPost, ActionName("Details")]
    public ActionResult AddJoin( int flavorId, Treat treat)
    {
      #nullable enable
      FlavorTreat ? check = _db.FlavorTreats.FirstOrDefault(j => (j.FlavorId == flavorId && j.TreatId == treat.TreatId)); 
      #nullable disable
      if (check == null && flavorId !=0)
      { 
        FlavorTreat join = new FlavorTreat {TreatId = treat.TreatId, FlavorId = flavorId};
        _db.FlavorTreats.Add(join); 
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId});
    }          
    
    [HttpPost]
    public ActionResult DeleteJoin (int joinId, int trId)
    {
      FlavorTreat join = _db.FlavorTreats.FirstOrDefault(j => j.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(join); 
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = trId});
    }

    [HttpPost]
    public ActionResult Delete (int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(t => t.TreatId == id);
      _db.Treats.Remove(thisTreat); 
      _db.SaveChanges(); 
      return RedirectToAction("Index", "Home");
    }

    public ActionResult Edit (int id) 
    {
      Treat treat = _db.Treats.FirstOrDefault(t => t.TreatId == id);
      return View(treat);
    }

    [HttpPost]
    public ActionResult Edit (Treat treat) 
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {        
        _db.Treats.Update(treat);
        _db.SaveChanges();
        return RedirectToAction("Index", "Home");
      }
    }
  }
}

PierresTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat

<h2>Add A New Treat</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <button type="submit" class="btn btn-secondary">Add</button>
}

<p>Go back to the @Html.ActionLink("Home Page", "Index", "Home")</p>

PierresTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat
<h2>@Model.Name</h2>
<br>
<p>These are the flavors associated with @Model.Name : </p>


@if (Model.JoinEntities.Count == 0)
{
  <p>There aren't any flavors assigned to this treat yet</p>
}
@if (!User.Identity.IsAuthenticated && Model.JoinEntities.Count > 0)
  {
    @foreach (FlavorTreat join in ViewBag.Joins)
    {
      <p>@join.Flavor.Name</p>
    }
  }
  
@if (User.Identity.IsAuthenticated && Model.JoinEntities.Count > 0)
{
  @foreach(FlavorTreat join in Model.JoinEntities)
  {
    <div class="row" id="list">
      <div class="col-8">
        <p>@join.Flavor.Name</p>
      </div>
      <div class="col-4">        
        @using(Html.BeginForm("DeleteJoin", "Treats"))
        {
          @Html.Hidden("joinId", join.FlavorTreatId)
          @Html.Hidden("trId", Model.TreatId)            
          <input type="submit" value="X">
        }        
      </div>
    </div>    
  }
}

@if (User.Identity.IsAuthenticated)
{
  <br>
  <h4>Add a new flavor to @Model.Name</h4>
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)
    @Html.Label("Choose a flavor to add")
    @Html.DropDownList("FlavorId")
    <button type="submit" class="btn btn-secondary">Add Flavor</button>
  }
  <br>
  @Html.ActionLink($"Edit {Model.Name}", "Edit", "Treats", new {id = Model.TreatId})
  <br>
  @using (Html.BeginForm("Delete", "Treats"))
  {
    @Html.Hidden("id", new {id = Model.TreatId})
    <button type="submit" class="btn btn-secondary">Remove This Treat</button>    
  }
}
<br>
<p>Go back to the @Html.ActionLink("Home Page", "Index", "Home")</p>

@if (!User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Log In", "Login", "Account") to your account to make changes</p>

  <p>Don't have an account? @Html.ActionLink("Create A New Account", "Register", "Account")</p>
}

PierresTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h2>Edit @Model.Name</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm("Edit", "Treats"))
{
  @Html.HiddenFor(model => model.TreatId)
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <button type="submit" class="btn btn-secondary">Edit</button>
}

<p>Go back to the @Html.ActionLink("Home Page", "Index", "Home")</p>

PierresTreats/Views/Treats/ReadOnly.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
<h2>@Model.Name</h2>
<br>
<p>These are the flavors associated with @Model.Name : </p>


@if (Model.JoinEntities.Count == 0)
{
  <p>There aren't any flavors assigned to this treat yet</p>
}
else 
{
  @foreach (string name in ViewBag.Names)
  {
    <p>@name</p>
  }
}

<br>
<p>Go back to the @Html.ActionLink("Home Page", "Index", "Home")</p>
<br>
<p>@Html.ActionLink("Log In", "Login", "Account") to your account to make changes</p>
<br>
<p>Don't have an account? @Html.ActionLink("Create A New Account", "Register", "Account")</p>