PierresTreats/Models/Flavor.cs
using System.Collections.Generic; 
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models;

public class Flavor
{
  public int FlavorId { get; set; }
  [Required(ErrorMessage = "The flavor must have a name")]
  public string Name { get; set; }
  public List<FlavorTreat> JoinEntities { get; }
  public ApplicationUser User { get; set; }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult ReadOnly(int id)
    {
      if (User.Identity.IsAuthenticated)
      {
        return RedirectToAction("Details", new {id = id});
      }
      else
      {
        Flavor thisFlavor = _db.Flavors
            .Include(f => f.JoinEntities)
            .ThenInclude(j => j.Treat)
            .FirstOrDefault(f => f.FlavorId == id);
            
        List<string> names = new List<string>();
        foreach (FlavorTreat join in _db.FlavorTreats)
        {
          if (join.FlavorId == thisFlavor.FlavorId)
          {
            names.Add(join.Treat.Name);
          }
        }
        ViewBag.Names = names;
        return View (thisFlavor);
      }
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index", "Home");
      }
    }
    public ActionResult Details (int id)
    {      
      Flavor thisFlavor = _db.Flavors
            .Include(flav => flav.JoinEntities)
            .FirstOrDefault(flav => flav.FlavorId == id);        
      List<Treat> select = new List<Treat>();
      foreach (Treat treat in _db.Treats)
      {      
        select.Add(treat);        
      }
      foreach (FlavorTreat join in thisFlavor.JoinEntities)
      {
        select.Remove(join.Treat);
      }
      ViewBag.TreatId = new SelectList(select, "TreatId", "Name");           
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Details")]
    public ActionResult AddJoin( int treatId, Flavor flavor)
    {
      #nullable enable
      FlavorTreat ? check = _db.FlavorTreats.FirstOrDefault(j => (j.TreatId == treatId && j.FlavorId == flavor.FlavorId)); 
      #nullable disable
      if (check == null && treatId !=0)
      { 
        FlavorTreat join = new FlavorTreat {TreatId = treatId, FlavorId = flavor.FlavorId};
        _db.FlavorTreats.Add(join); 
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId});
    }  

    [HttpPost]
    public ActionResult DeleteJoin (int joinId, int flavId)
    {
      FlavorTreat join = _db.FlavorTreats.FirstOrDefault(j => j.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(join); 
      _db.SaveChanges();
      return RedirectToAction("Details", new {id = flavId});
    }

    [HttpPost]
    public ActionResult Delete (int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(f => f.FlavorId == id);
      _db.Flavors.Remove(thisFlavor); 
      _db.SaveChanges(); 
      return RedirectToAction("Index", "Home");
    }
  }
}

PierresTreats/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h2>Add A New Flavor</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <button type="submit" class="btn btn-secondary">Add</button>
}

<p>Go back to the @Html.ActionLink("Home Page", "Index", "Home")</p>

PierresTreats/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Flavor

<h2>@Model.Name</h2>
<br>
<p>These are the treats associated with @Model.Name : </p>


@if (Model.JoinEntities.Count == 0)
{
  <p>There aren't any treats assigned to this flavor yet</p>
}
else 
{
  @foreach(FlavorTreat join in Model.JoinEntities)
  {
    <div class="row" id="list">
      <div class="col-8">
        <p>@join.Treat.Name</p>
      </div>
      <div class="col-4">            
        @using(Html.BeginForm("DeleteJoin", "Flavors"))
        {
          @Html.Hidden("joinId", join.FlavorTreatId)
          @Html.Hidden("flavId", Model.FlavorId)            
          <input type="submit" value="X">
        }        
      </div>
    </div>    
  }
}

@if (User.Identity.IsAuthenticated)
{
  <br>
  <h4>Add a new treat to @Model.Name</h4>
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)
    @Html.Label("Choose a treat to add")
    @Html.DropDownList("TreatId")
    <button type="submit" class="btn btn-secondary">Add Treat</button>
  }
  <br>
  @using (Html.BeginForm("Delete", "Flavors"))
  {
    @Html.Hidden("id", new {id = Model.FlavorId})
    <button type="submit" class="btn btn-secondary">Remove This Flavor</button>    
  }

}
<br>
<p>Go back to the @Html.ActionLink("Home Page", "Index", "Home")</p>

@if (!User.Identity.IsAuthenticated)
{
  <p>@Html.ActionLink("Log In", "Login", "Account") to your account to make changes</p>

  <p>Don't have an account? @Html.ActionLink("Create A New Account", "Register", "Account")</p>
}

PierresTreats/Views/Flavors/ReadOnly.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
<h2>@Model.Name</h2>
<br>
<p>These are the treats associated with @Model.Name : </p>


@if (Model.JoinEntities.Count == 0)
{
  <p>There aren't any treats assigned to this treat yet</p>
}
else 
{
  @foreach (string name in ViewBag.Names)
  {
    <p>@name</p>
  }
}
<br>
<p>Go back to the @Html.ActionLink("Home Page", "Index", "Home")</p>
<br>
<p>@Html.ActionLink("Log In", "Login", "Account") to your account to make changes</p>
<br>
<p>Don't have an account? @Html.ActionLink("Create A New Account", "Register", "Account")</p>